### ISSUE TITLE
Chrome Console: "TypeError: e.deleteUser is not a function" on local installation & demo website

### ISSUE THREAD

**Issue by mapl** [erguotou520/vue-fullstack#10]
Hello,

when trying to delete a user on https://vue-fullstack-demo.herokuapp.com/users , you will receive an error

> UserList.vue?a9e7:73 Uncaught TypeError: e.deleteUser is not a function
>    at Object.click [as fn] (UserList.vue?a9e7:73)
>    at HTMLButtonElement.<anonymous> (vue.runtime.common.js:2748)

**Comment by erguotou520** [comment]
[fixed](https://github.com/erguotou520/vue-fullstack/commit/103acce5f97170c2e9093a4459123b4a48ab3ba4) by change `inline-template` to `scoped slot`
