### ISSUE TITLE
Demo Page Login fails

### ISSUE THREAD

**Issue by mapl** [erguotou520/vue-fullstack#14]
Demo Page Login fails when using credentials: admin/admin:

message.error
login.authFail

**Comment by erguotou520** [comment]
someone changed the password, but the message is not correct

**Comment by KL-Kim** [comment]
Got the error
"POST http://localhost:9001/api/auth/local 404 (Not Found)"

**Comment by erguotou520** [comment]
I didn't get the post error. Could you please show me the steps to reproduce? @KL-Kim

**Comment by KL-Kim** [comment]
$ vue init erguotou520/vue-fullstack vueFullstack

? Project name vue-fullstack
? Project description A vue-fullstack project
? Author KL-Kim <jinguanglong11@hotmail.com>
? Use real backend server or mock server Backend
? Port that backend server listen at development environment 9000
? Port that frontend server listen at development environment 9001
? MongoDB uri, '-dev' will be appended in development, default is local uri 
? Need vue-i18n? Yes

$ npm install
$ npm run server

I can see that admin user is added to mongodb.

$ npm run client

In the login page, but I failed to login with admin/admin, and I can saw the error message from browser console.

**Comment by erguotou520** [comment]
@KL-Kim  fixed in https://github.com/erguotou520/vue-fullstack/commit/1e518d916c3d5256ca68c0bff23776759f62e2ea

**Comment by KL-Kim** [comment]
Awesome! @erguotou520

**Comment by erguotou520** [comment]
Currently I change the demo project to be generated by `travis-ci` automatically after a lot of attempts, and the login message was fixed. So close this issue.
