### ISSUE TITLE
请问一下，示例中el-table自适应高度是怎么做到的

### ISSUE THREAD

**Issue by shennwei** [erguotou520/vue-fullstack#16]
你好，我在flex布局的div中添加el-table并设置height=‘100%’，但是没有效果，想请问一下如何才能让el-table自适应高度

**Comment by shennwei** [comment]
按照你的代码搞定了，谢谢分享。
希望能在element的layout中加上一些经典布局，
如https://ant.design/components/layout-cn/

**Comment by erguotou520** [comment]
都大同小异吧
