### ISSUE TITLE
点击一次链接，会执行两次 changeRouteLoading,CHANGE

### ISSUE THREAD

**Issue by inhere** [erguotou520/vue-fullstack#2]
如下图

![image](https://cloud.githubusercontent.com/assets/5302062/20873385/deb7d280-bae1-11e6-870b-239b950af349.png)

**Comment by erguotou520** [comment]
[fixed](https://github.com/erguotou520/vue-fullstack/commit/a5111e532ee7d1d44e6844d08564be4fb5d5301d)
