### ISSUE TITLE
Sorting is only client side

### ISSUE THREAD

**Issue by skrichten** [erguotou520/vue-fullstack#22]
Nice project so far!  I've been working on a project with Element UI and running into the same problem you have here...  Although the server side pagination works, the sorting only happens client side.  So the sort only uses the current page of data.  Most people would expect the sorting to account for all the data, not just the current page.  Unfortunately Element UI doesn't seem to provide an easy way to manage this.  Maybe there is some way to implement it using a combination of the 'header-click' event and the column 'render-header' function?  I might resort to ditching the el-table component altogether because of this.

**Comment by erguotou520** [comment]
`Element UI`'s table is designed to sort on the client at first. It support `header-click` and `sort-change` event now, you may implement your need with these 2 events.

**Comment by skrichten** [comment]
Ummm, yeah that is pretty much what I just said.  Except I'm not sure sort change event will be helpful.  It would be if it would allow aborting/replacing the client side sort, but as far as I can tell, that is not the case.  I think you would have to disable the built in sort first and then replace it using header-click.  Then maybe render-header could be used to output your own arrow indicators, but that property is not very well documented.

Do you not have any interest in implementing this in your project?  You have the server side pagination so it seems like a good idea.

**Comment by erguotou520** [comment]
I am going to talk with their developer for your solution.

**Comment by skrichten** [comment]
Hi, just checking in to see if you have any new thoughts/info on this.  On my end, I got the server side sorting working fine using the header-click event.  I'm looking into using the render-header function to properly display the indicator arrows now.  Having some trouble with that part.

**Comment by skrichten** [comment]
FYI...
https://github.com/ElemeFE/element/issues/5161

**Comment by erguotou520** [comment]
`ElementUI` now support `custom sortable`, you need to set table-column's `sortable` to `custom` and listen to table's `sort-change` method.

**Comment by skrichten** [comment]
I don't see this in their documentation.

**Comment by erguotou520** [comment]
It has not been translated to en currently 😿 , you can switch to Chinese document.
