### ISSUE TITLE
新手，打扰问一下 

### ISSUE THREAD

**Issue by inhere** [erguotou520/vue-fullstack#3]
`client/build/webpack.base.conf.js` 里面的两个 `fallback` 中的 `node_modules` 路径

是这样

```
fallback: [path.join(__dirname, '../node_modules')]
```

还是

```
fallback: [path.join(__dirname, '../../node_modules')]
```

**Comment by erguotou520** [comment]
我的锅，有些路径可能漏改了，[fixed](https://github.com/erguotou520/vue-fullstack/commit/42da3e146ec8c7a33c3772cb3f69c66c335ea628#diff-8bb94eed8df723eeb43835a11113363bR17)
