### ISSUE TITLE
Issue when doing vue init

### ISSUE THREAD

**Issue by rudolph2907** [erguotou520/vue-fullstack#4]
Hi 

I am trying to use your template by running the vue init command, but I run in to problem when getting to vue-i18n: Need vue-i18n? Yes
   vue-cli · Parse error on line 11:
...tive="showConfig">{{$t('header.settings'
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

**Comment by erguotou520** [comment]
Refer to #1
