### ISSUE TITLE
When choosing not to install i18n module, it doesn't run correctly.

### ISSUE THREAD

**Issue by rudolph2907** [erguotou520/vue-fullstack#5]

**Comment by erguotou520** [comment]
Yes, I haven't removed `i18n` syntax `$t` when not choose i18n module, I'll be working on it.

**Comment by erguotou520** [comment]
[fixed](https://github.com/erguotou520/vue-fullstack/commit/4d0b30bd22f1f608fac068d719456dfc6f607eda)
You need to run `npm run remove:i18n` manually after `npm install` if you choose no to install i18n.

**Comment by erguotou520** [comment]
Sorry, still contains error, I will fix later.

**Comment by erguotou520** [comment]
The previous fixed compile error, but still contains some runtime error, [this](https://github.com/erguotou520/vue-fullstack/commit/b3f463eaa9add3ac104b263657bc79177e1bcd0a) fixed the vue runtime error, please note that  `change locale` function in `/client/src/components/Header.vue` still reserved, you can remove those code manually.

**Comment by erguotou520** [comment]
when `vue-cli` add the finish hook I will remove this script and go to run this script automatically.
