### ISSUE TITLE
模仿你的例子，语言切换不成功

### ISSUE THREAD

**Issue by hym1884603** [erguotou520/vue-fullstack#6]
![image](https://cloud.githubusercontent.com/assets/16299739/21420770/71031646-c86a-11e6-9bc7-6312edd983c0.png)
![image](https://cloud.githubusercontent.com/assets/16299739/21420777/7728d056-c86a-11e6-830a-e43cab8c1438.png)
会出现这种情况是为什么 模仿你的代码 用vuex 里面的action 发布 updateLocale

**Comment by erguotou520** [comment]
这个是因为没有找到对应的语言文字，在`/client/src/locale/[zh_CN|en_US].js`文件中添加响应的语言配置项就可以了，可以参考我默认添加的
```js
el: {
  select: {
    noData: '无匹配数据'
  }
}
```
